site_name: Elijjah
theme:
  name: material
  palette:
    scheme: preference
  font: false
repo_url: https://gitlab.com/elijah-team/elijah-lang/
repo_name: elijah-team/elijah-lang
plugins:
  - git-revision-date
