site_name: The Elijjah Programming Language
theme:
  name: material
  palette:
    scheme: preference
  font: false
repo_url: https://gitlab.com/elijah-team/elijah-lang/
repo_name: elijah-team/elijah-lang
plugins:
  - git-revision-date-localized
markdown_extensions:
  - def_list

nav:
  - index.md
  - language-overview.md
  - Language:
    - access_notation.md
    - aliases.md
    - type_names.md
 - Concepts:
    - keywords.md
    - special_words.md
    - structure.md

